name: owpet
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.2
  firebase_core: ^2.31.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  sqflite: ^2.3.3
  intl: ^0.18.1
  file_picker: ^8.0.3
  firebase_storage: ^11.7.6
  carousel_slider: ^4.2.1
  share: ^2.0.4
  share_plus: ^9.0.0
  motion_tab_bar_v2: ^0.3.0
  firebase_auth: ^4.19.6
  provider: ^6.1.2
  flutter_calendar_carousel: ^2.4.3
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.3
  syncfusion_flutter_charts: ^25.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  image_path: assets/images/logo.png
  android: true
  ios: true
  adaptive_icon_background: "#00FFFFFF"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
