// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAiRQ0GuRjprWfPLov-9W4JhyaJyNoFwg',
    appId: '1:814449029472:web:6318b3f288eddd989d6e05',
    messagingSenderId: '814449029472',
    projectId: 'owpet-app',
    authDomain: 'owpet-app.firebaseapp.com',
    storageBucket: 'owpet-app.appspot.com',
    measurementId: 'G-TQF88N77BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTekf3tfFl_ZCwpoTevX8Zs294a1k_hSg',
    appId: '1:814449029472:android:98a8aaecee17bb959d6e05',
    messagingSenderId: '814449029472',
    projectId: 'owpet-app',
    storageBucket: 'owpet-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqCAnjx2jNLzG6t3yhukXJWcI9x4moZeY',
    appId: '1:814449029472:ios:6f5d511e5ecde2fd9d6e05',
    messagingSenderId: '814449029472',
    projectId: 'owpet-app',
    storageBucket: 'owpet-app.appspot.com',
    iosBundleId: 'com.example.owpet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqCAnjx2jNLzG6t3yhukXJWcI9x4moZeY',
    appId: '1:814449029472:ios:6f5d511e5ecde2fd9d6e05',
    messagingSenderId: '814449029472',
    projectId: 'owpet-app',
    storageBucket: 'owpet-app.appspot.com',
    iosBundleId: 'com.example.owpet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAiRQ0GuRjprWfPLov-9W4JhyaJyNoFwg',
    appId: '1:814449029472:web:0bed0cbfb718edc59d6e05',
    messagingSenderId: '814449029472',
    projectId: 'owpet-app',
    authDomain: 'owpet-app.firebaseapp.com',
    storageBucket: 'owpet-app.appspot.com',
    measurementId: 'G-MKLXHL04GY',
  );
}
